import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Card, Pill, Progress, Screen, Section, s } from '@/components';
import { colors } from '@/theme';
import { useCourseProgress, useCourses } from '@/data/hooks';
export default function Learn() { const { data: courseRows = [] } = useCourses(); const { data: progressRows = [] } = useCourseProgress(); const palette = [colors.blue, colors.green, colors.coral]; const courses = courseRows.map((course, index) => { const progress = progressRows.find((item) => item.courseId === course.id); return { ...course, faculty: course.facultyId ? 'Assigned faculty' : 'Faculty team', progress: progress?.percent ?? 0, lessons: progress?.total ?? 0, color: palette[index % palette.length] }; }); const lessonCount = courses.reduce((total, course) => total + course.lessons, 0); const average = courses.length ? Math.round(courses.reduce((total, course) => total + course.progress, 0) / courses.length) : 0; const onTrack = courses.filter((course) => course.progress >= 75).length; return <Screen title="My learning" subtitle={`${courses.length} active courses · Current semester`}>
  <View style={l.stats}><Card style={l.stat}><Text style={l.statValue}>{lessonCount}</Text><Text style={s.body}>Lessons</Text></Card><Card style={l.stat}><Text style={l.statValue}>{average}%</Text><Text style={s.body}>Average</Text></Card><Card style={l.stat}><Text style={l.statValue}>{onTrack}</Text><Text style={s.body}>On track</Text></Card></View>
  <Section title="Courses">{courses.map((course, index) => <Pressable key={course.id} accessibilityRole="button" accessibilityLabel={`Continue ${course.title}`} onPress={() => router.push(`/course/${course.id}`)}><Card style={{ gap: 12 }}><View style={s.between}><View style={[l.courseIcon, { backgroundColor: course.color }]}><Text style={l.courseIconText}>{course.code.slice(0, 2)}</Text></View><Pill text={index === 2 ? 'On track' : 'In progress'} tone={index === 2 ? 'green' : 'blue'} /></View><View><Text style={l.code}>{course.code}</Text><Text style={l.title}>{course.title}</Text><Text style={s.body}>{course.faculty} · {course.lessons} lessons</Text></View><Progress value={course.progress} color={course.color} /><View style={s.between}><Text style={l.small}>{course.progress}% complete</Text><View style={l.open}><Text style={l.openText}>Continue</Text><Ionicons name="chevron-forward" size={15} color={colors.blue} /></View></View></Card></Pressable>)}</Section>
  <Section title="Offline learning"><Card><View style={s.between}><View style={{ flex: 1, marginRight: 12 }}><Text style={l.title}>Course cache</Text><Text style={s.body}>Course details stay readable after they have loaded. Media files need an explicit download.</Text></View><Pill text="Local" tone="green" /></View></Card></Section>
</Screen>; }
const l = StyleSheet.create({ stats: { flexDirection: 'row', gap: 8 }, stat: { flex: 1, padding: 13 }, statValue: { color: colors.ink, fontSize: 21, fontWeight: '900' }, courseIcon: { width: 46, height: 46, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, courseIconText: { color: 'white', fontWeight: '900' }, code: { color: colors.blue, fontSize: 11, fontWeight: '900' }, title: { color: colors.ink, fontSize: 17, fontWeight: '800', marginVertical: 3 }, small: { color: colors.muted, fontSize: 11, fontWeight: '700' }, open: { flexDirection: 'row', alignItems: 'center', gap: 2 }, openText: { color: colors.blue, fontWeight: '800', fontSize: 12 } });
