import { useEffect } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Button, Card, Pill, Screen, Section, s } from '@/components';
import { can, roleLabels, roles } from '@/domain';
import { useAppStore } from '@/store';
import { colors } from '@/theme';
import { useProfile } from '@/data/hooks';
import { useAuth } from '@/auth';
import Ionicons from '@expo/vector-icons/Ionicons';
export default function Profile() { const { role, setRole, online } = useAppStore(); const auth = useAuth(); const { data: profile } = useProfile(); const activeRole = profile?.role ?? role; const fallbackName = auth.configured ? 'Student' : 'Adithya Kumar'; useEffect(() => { if (profile?.role) setRole(profile.role); }, [profile?.role, setRole]); const initials = (profile?.fullName || fallbackName).split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase(); return <Screen title="Profile" subtitle="Personal settings and role workspace">
  <Card style={p.identity}><View style={p.avatar}><Text style={p.initials}>{initials}</Text></View><View style={{ flex: 1 }}><Text style={p.name}>{profile?.fullName || fallbackName}</Text><Text style={s.body}>{profile?.department || (auth.configured ? 'Department not set' : 'Computer Science')}{profile?.yearOfStudy ? ` · Year ${profile.yearOfStudy}` : ''}{profile?.semester ? ` · Semester ${profile.semester}` : ''}{profile?.section ? ` · Section ${profile.section}` : ''}</Text><Pill text={roleLabels[activeRole]} tone="blue" /></View></Card>
  {!auth.configured && <Section title="Demo role switcher"><Card><Text style={s.body}>Preview the role-aware shell. When Supabase is connected, the signed-in profile and RLS policies replace this switcher.</Text><View style={p.roles}>{roles.map((r) => <Pressable key={r} onPress={() => setRole(r)} style={[p.role, role === r && p.roleActive]}><Text style={[p.roleText, role === r && p.roleTextActive]}>{roleLabels[r]}</Text></Pressable>)}</View></Card></Section>}
  {activeRole !== 'student' && <Section title="Role workspace"><Card><Text style={p.workspace}>{can(activeRole, 'manage_platform') ? 'Platform controls' : can(activeRole, 'manage_department') ? 'Department operations' : can(activeRole, 'grade') ? 'Teaching workspace' : can(activeRole, 'mentor') ? 'Mentee overview' : 'Club publishing'}</Text><Text style={s.body}>Actions are scoped for {roleLabels[activeRole].toLowerCase()} accounts and enforced again in database policies.</Text><View style={{ marginTop: 12 }}><Button label="Open workspace" onPress={() => router.push('/workspace')} /></View></Card></Section>}
  <Section title="Account"><Card><Pressable onPress={() => router.push('/notifications')} style={p.setting}><Text style={p.settingName}>Notifications</Text><View style={p.settingEnd}><Text style={p.settingValue}>Open</Text><Ionicons name="chevron-forward" size={16} color={colors.muted} /></View></Pressable><Pressable onPress={() => router.push('/credits')} style={p.setting}><Text style={p.settingName}>Credits & licenses</Text><View style={p.settingEnd}><Text style={p.settingValue}>Open</Text><Ionicons name="chevron-forward" size={16} color={colors.muted} /></View></Pressable>{[['Course cache', 'On device'], ['Offline sync', online ? 'Up to date' : 'Waiting for network'], ['Privacy & security', 'Protected']].map(([a, b]) => <View key={a} style={p.setting}><Text style={p.settingName}>{a}</Text><Text style={p.settingValue}>{b}</Text></View>)}</Card></Section>
  {auth.configured && <Button label="Sign out" secondary onPress={() => void auth.signOut()} />}
  <Text style={p.version}>LearnFlow MVP · Android-first · {auth.configured ? 'Secure account data' : 'Demo data'}</Text>
</Screen>; }
const p = StyleSheet.create({ identity: { flexDirection: 'row', alignItems: 'center', gap: 15 }, avatar: { width: 64, height: 64, borderRadius: 22, backgroundColor: colors.navy, alignItems: 'center', justifyContent: 'center' }, initials: { color: 'white', fontSize: 20, fontWeight: '900' }, name: { color: colors.ink, fontSize: 20, fontWeight: '900', marginBottom: 2 }, roles: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 14 }, role: { borderWidth: 1, borderColor: colors.line, paddingHorizontal: 11, paddingVertical: 8, borderRadius: 10 }, roleActive: { backgroundColor: colors.navy, borderColor: colors.navy }, roleText: { color: colors.muted, fontSize: 11, fontWeight: '800' }, roleTextActive: { color: 'white' }, workspace: { color: colors.ink, fontSize: 17, fontWeight: '900', marginBottom: 4 }, setting: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.line }, settingEnd: { flexDirection: 'row', alignItems: 'center', gap: 4 }, settingName: { color: colors.ink, fontWeight: '700' }, settingValue: { color: colors.muted, fontSize: 12 }, version: { color: colors.muted, textAlign: 'center', fontSize: 11, marginTop: 18 } });
