import { StyleSheet, Text, View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { Card, Pill, Progress as Bar, Screen, Section, s } from '@/components';
import { colors } from '@/theme';
import { useAchievements, useAttendance, useCourseProgress, useCourses } from '@/data/hooks';
export default function ProgressScreen() { const { data: courseRows = [] } = useCourses(); const { data: progressRows = [] } = useCourseProgress(); const { data: attendance = [] } = useAttendance(); const { data: achievements = [] } = useAchievements(); const palette = [colors.blue, colors.green, colors.coral]; const subjects = courseRows.map((course, index) => ({ name: course.title, value: progressRows.find((item) => item.courseId === course.id)?.percent ?? 0, color: palette[index % palette.length] })); const badges = achievements.length ? achievements.slice(0, 3).map((item) => item.title) : ['Start a streak', 'Complete a quiz', 'Attend class']; return <Screen title="Progress" subtitle="A clear view of your semester">
  <Card style={p.overview}><View><Text style={p.big}>{achievements.length}</Text><Text style={p.outOf}>milestones</Text></View><View style={{ flex: 1 }}><Pill text="LIVE DATA" tone="green" /><Text style={p.overTitle}>Learning health</Text><Text style={s.body}>Updates as lessons and achievements are recorded</Text></View></Card>
  <View style={p.stats}><Card style={p.stat}><Ionicons name="trophy-outline" size={20} color={colors.blue} /><Text style={p.value}>{achievements.length}</Text><Text style={s.body}>Achievements</Text></Card><Card style={p.stat}><Ionicons name="book-outline" size={20} color={colors.blue} /><Text style={p.value}>{courseRows.length}</Text><Text style={s.body}>Courses</Text></Card><Card style={p.stat}><Ionicons name="checkmark-done-outline" size={20} color={colors.blue} /><Text style={p.value}>{attendance.length}</Text><Text style={s.body}>Attendance records</Text></Card></View>
  <Section title="Course progress">{subjects.map((x) => <Card key={x.name}><View style={s.between}><Text style={p.course}>{x.name}</Text><Text style={[p.valueSmall, { color: x.color }]}>{x.value}%</Text></View><View style={{ marginTop: 12 }}><Bar value={x.value} color={x.color} /></View></Card>)}</Section>
  <Section title="Achievements"><View style={p.badges}>{badges.map((x, i) => <Card key={x} style={p.badge}><View style={p.badgeIcon}><Ionicons name={(['flame', 'star', 'sunny'] as const)[i]} size={20} color={colors.blue} /></View><Text style={p.badgeText}>{x}</Text></Card>)}</View></Section>
  <Section title="Mentor support"><Card style={{ backgroundColor: colors.sky }}><Text style={p.note}>Your assigned mentor can review permitted progress and attendance, without access to change grades or roles.</Text></Card></Section>
</Screen>; }
const p = StyleSheet.create({ overview: { backgroundColor: colors.navy, borderColor: colors.navy, flexDirection: 'row', alignItems: 'center', gap: 18 }, big: { color: 'white', fontSize: 46, fontWeight: '900' }, outOf: { color: '#C7D2FE', textAlign: 'center', marginTop: -8 }, overTitle: { color: 'white', fontSize: 18, fontWeight: '900', marginTop: 9 }, stats: { flexDirection: 'row', gap: 8, marginTop: 8 }, stat: { flex: 1, padding: 12 }, value: { color: colors.ink, fontSize: 20, fontWeight: '900', marginTop: 6 }, course: { color: colors.ink, fontWeight: '800', flex: 1 }, valueSmall: { fontWeight: '900' }, badges: { flexDirection: 'row', gap: 8 }, badge: { flex: 1, padding: 12, minHeight: 95 }, badgeIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: colors.sky, alignItems: 'center', justifyContent: 'center' }, badgeText: { color: colors.ink, fontWeight: '800', fontSize: 12, marginTop: 8 }, note: { color: colors.navy, fontSize: 15, lineHeight: 22, fontWeight: '600' } });
