import { StyleSheet, Text, View } from 'react-native';
import { Card, Pill, Screen, Section, s } from '@/components';
import { colors } from '@/theme';
import { useSocialPosts } from '@/data/hooks';
import { formatDateTime } from '@/domain';
export default function Social() { const { data: posts = [] } = useSocialPosts(); return <Screen title="Sairam Social" subtitle="Verified campus updates, clubs and student life">
  <View style={x.filters}>{['For you', 'Departments', 'Clubs', 'Events'].map((f, i) => <View key={f} style={[x.filter, i === 0 && x.active]}><Text style={[x.filterText, i === 0 && x.activeText]}>{f}</Text></View>)}</View>
  <Section title="Campus feed">{posts.map((post, index) => { const author = post.clubName || 'Sri Sairam'; return <Card key={post.id}><View style={s.row}><View style={[x.logo, { backgroundColor: index % 2 ? colors.green : colors.blue }]}><Text style={x.logoText}>{author.slice(0, 2).toUpperCase()}</Text></View><View style={{ flex: 1 }}><Text style={x.author}>{author}</Text><View style={s.row}><Pill text="Verified" tone="green" /><Text style={x.time}> · {formatDateTime(post.publishedAt)}</Text></View></View></View><Text style={x.post}>{post.body}</Text>{post.mediaUrls.length > 0 && <View style={x.media}><Text style={x.mediaMark}>SAIRAM</Text><Text style={x.mediaTitle}>CAMPUS UPDATE</Text><Text style={x.mediaBody}>Approved media attachment</Text></View>}</Card>; })}</Section>
  <Card style={x.safety}><Text style={x.safetyTitle}>A safer campus feed</Text><Text style={s.body}>Only approved college adapters can import or publish external content. Links and media are validated before they enter LearnFlow.</Text></Card>
</Screen>; }
const x = StyleSheet.create({ filters: { flexDirection: 'row', gap: 7, marginBottom: 4 }, filter: { paddingHorizontal: 13, paddingVertical: 9, borderRadius: 99, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line }, active: { backgroundColor: colors.navy, borderColor: colors.navy }, filterText: { color: colors.muted, fontSize: 11, fontWeight: '800' }, activeText: { color: 'white' }, logo: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginRight: 11 }, logoText: { color: 'white', fontWeight: '900', fontSize: 11 }, author: { color: colors.ink, fontWeight: '900' }, time: { color: colors.muted, fontSize: 11 }, post: { color: colors.ink, fontSize: 14, lineHeight: 21, marginVertical: 14 }, media: { backgroundColor: colors.navy, borderRadius: 16, minHeight: 160, padding: 20, justifyContent: 'flex-end', overflow: 'hidden' }, mediaMark: { color: colors.gold, fontSize: 10, fontWeight: '900', letterSpacing: 2 }, mediaTitle: { color: 'white', fontSize: 23, fontWeight: '900', marginTop: 6 }, mediaBody: { color: '#C4D5DD', marginTop: 4 }, safety: { backgroundColor: colors.mint, borderColor: '#C3DED4', marginTop: 14 }, safetyTitle: { color: colors.green, fontWeight: '900', fontSize: 16, marginBottom: 4 } });
