import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Card, Button, EmptyState, Pill, Progress, Screen, Section, s } from '@/components';
import { colors } from '@/theme';
import { useCourseProgress, useCourses, useLessons } from '@/data/hooks';
export default function Course() { const { id = '' } = useLocalSearchParams<{ id: string }>(); const { data: courses = [] } = useCourses(); const { data: lessons = [] } = useLessons(id); const { data: progressRows = [] } = useCourseProgress(); const course = courses.find((x) => x.id === id); if (!course) return <Screen title="Course"><EmptyState icon="book-outline" title="Course unavailable" text="This course may not be published or assigned to your account." /></Screen>; const next = lessons[0]; const progress = progressRows.find((item) => item.courseId === id)?.percent ?? 0; const resourceCount = lessons.reduce((total, lesson) => total + lesson.resourceUrls.length, 0); return <Screen title={course.title} subtitle={`${course.code} · ${course.department || 'Sri Sairam'}`}>
  <Card style={[c.hero, { backgroundColor: colors.blue, borderColor: colors.blue }]}><Pill text={`${progress}% COMPLETE`} tone="gold" /><Text style={c.heroTitle}>{next?.title || 'Course overview'}</Text><Text style={c.heroBody}>{next?.summary || course.description || 'Learning materials will appear here.'}</Text><Progress value={progress} color={colors.gold} />{next && <Button label="Start lesson" onPress={() => router.push(`/lesson/${next.id}`)} />}</Card>
  <Section title="Lessons">{lessons.length === 0 ? <EmptyState icon="document-text-outline" title="No published lessons" text="Your faculty will publish the next lesson here." /> : lessons.map((lesson, i) => <Pressable key={lesson.id} onPress={() => router.push(`/lesson/${lesson.id}`)}><Card style={c.module}><View style={c.number}><Text style={c.numberText}>{i + 1}</Text></View><View style={{ flex: 1 }}><Text style={c.moduleTitle}>{lesson.title}</Text><Text style={s.body}>{lesson.summary || (lesson.videoUrl ? 'Video lesson' : 'Reading lesson')}</Text></View></Card></Pressable>)}</Section>
  <Section title="Resources"><Card><View style={s.between}><View><Text style={c.moduleTitle}>Course resources</Text><Text style={s.body}>{resourceCount} approved links across {lessons.length} lessons</Text></View><Pill text={resourceCount ? 'Available' : 'None yet'} tone={resourceCount ? 'green' : 'blue'} /></View></Card></Section>
</Screen>; }
const c = StyleSheet.create({ hero: { gap: 13 }, heroTitle: { color: 'white', fontSize: 24, lineHeight: 30, fontWeight: '900' }, heroBody: { color: '#DBEAFE' }, module: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14 }, number: { width: 34, height: 34, borderRadius: 12, backgroundColor: colors.sky, alignItems: 'center', justifyContent: 'center' }, done: { backgroundColor: colors.green }, numberText: { color: colors.blue, fontWeight: '900' }, moduleTitle: { color: colors.ink, fontWeight: '800', fontSize: 14 }, download: { color: colors.blue, fontWeight: '900', fontSize: 12 } });
